config/routes.rb
SantaClaraDeals::Application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root to: 'main#index'
  resources :consumers

  

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/business.rb
class Business < ActiveRecord::Base
  has_many :deals

  accepts_nested_attributes_for :deals
end

app/models/consumer.rb
class Consumer < ActiveRecord::Base
  validates_uniqueness_of :email, message: "Yay! You've already been added to the email list!"
  validates_presence_of :email, message: "Please enter an email address"
end

app/models/deal.rb
class Deal < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/businesses_controller.rb
class BusinessesController < ApplicationController
end

app/controllers/consumers_controller.rb
class ConsumersController < ApplicationController
  def create
    @consumer = Consumer.new
    @consumer.email = params[:email]
    if @consumer.save
      flash[:notice] = "You have been added to the email list!"
      redirect_to :root
    else
      flash[:alert] = @consumer.errors.values.join('. ')
      redirect_to :root
    end
  end
end

app/controllers/deals_controller.rb
class DealsController < ApplicationController
  def index
    @deals = Deal.order("created_at")
    @new_consumer = Consumer.new
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
    @deals = Deal.all
    @new_consumer = Consumer.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/deals/index.html.erb
<!-- Main Section of the Site -->
<header id="head">
  <div class="inner">
    <a href="#" class="logotext square"><h1>Santa Clara Deals</h1></a>
    <div class="details right">

      <div class="message">
        <!-- Fading text. See core.js for list of words. -->
        <p class="large">Find deals for <span id="words"></span></p>

        <!-- Static text -->
        <p class="medium">Finding great deals where there were none in Santa Clara, Sunnyvale, Campbell, Los Altos and Mountain View.</p>
        <p class="small">We're currently building our team and partnering with businesses to bring you the best deals in the area. Whether you're looking for cheap haircuts or discounts on sushi restaurants, you'll soon get it. Sign-up below so you don't miss out. </p>
      </div>

      <!-- Signup Form  -->
        <%= form_for @new_consumer, url: consumers_path(@musician), method: "post", html: {class: "newsletter", id: "subscribe"} do |f| %>
            <input type="email" id="email" name="email" class="email" placeholder="Enter your email..." /> <button>Sign Me Up!</button> 
          <p class="note">We won't spam you. Pinky swear.</p>
          <div id="container_flash">
            <% flash.each do |key, value| %>
              <div class='flash' id='<%= key %>'>
                <%= value %>
              </div>
            <% end %>
          </div>
        <% end %>
    </div>
  </div>
</header>

<!-- Footer Section -->
<section class="body">
  <br><br>
  <div class="inner">
    <div class="right_text">
       If you're a business with deals to offer, please contact us at info@santaclaradeals.com.
    </div>
    <div class="copyright">
      <p>&copy; 2013 <a href="http://danielhellier.com">Santa Clara Deals</a>.</p>
      <p>All Rights Reserved.</p>
    </div>
  </div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <%= favicon_link_tag 'red_dot.gif' %>
    <title>Santa Clara Deals | Great Deals in Santa Clara, Sunnyvale, Campbell and Los Altos</title>
    <meta name="description" content="Bringing great deals to the South Bay and Santa Clara County. Sign up today and get deals on restaurants, acitivities, services and products." />

    <!-- Google Web Fonts
     ================================================== -->
    <link href='http://fonts.googleapis.com/css?family=Lobster+Two:700|Bree+Serif|Muli' rel='stylesheet' type='text/css'>

    <!-- Mobile Specific Metas
     ================================================== -->
    <meta name="viewport" content="width=device-width">

    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>

    <!-- Javascript
     ================================================== -->
    <script src='http://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js'></script>
    <!-- <script src="//maps.googleapis.com/maps/api/js?sensor=false"></script> -->
    <!-- <script src="assets/js/supersized.js"></script> -->
    <style>

      #head  {
      background: url(<%= image_path('slider/chef.jpg') %>);
      -webkit-background-size: cover;
      -moz-background-size: cover;
      -o-background-size: cover;
      background-size: cover;
      }

    </style>
    <meta name="google-site-verification" content="fZ_gF6ISLhvJd20cowEMyuog_hhJn5fI4TRR1DOTTQQ" />
  </head>
  <body>

    <div class="container-fluid">
      <%= yield %>
    </div>

    <!-- Footer Section -->
    <section class="body">
      <div class="inner">
        <div class="copyright float_left">
          <p>&copy; 2013 Santa Clara Deals.</p>
          <p>All Rights Reserved.</p>
        </div>
        <br><br><br>
        <div class="right_text">
           If you're a business with deals to offer, please contact us at info@santaclaradeals.com.
        </div>
      </div>
    </section>

  </body>

  <script src=<% javascript_include_tag("core.js?asdasdasd") %> ></script>

  <!-- CODE FOR ANALYTICS-->
  <script type="text/javascript">

      var _gaq = _gaq || [];
     _gaq.push(['_setAccount', 'UA-38806309-1']);
     _gaq.push(['_trackPageview']);

     (function() {
       var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
       ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
       var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
     })();

  </script>
</html>

app/views/main/index.html.erb
<!-- Main Section of the Site -->
<header id="head">
  <div class="inner">
    <div class="row">
      <div class="span6">
        <a href="#" class="logotext square"><h1>Santa Clara Deals</h1></a>
      </div>
      <div class="span6">
        <div class="details right">

          <div class="message">
            <!-- Fading text. See core.js for list of words. -->
            <p class="large">Deals Where You Are.<span id="words"></span></p>

            <!-- Static text -->
            <p class="medium">Finding great deals where there were none in Santa Clara, Sunnyvale, Campbell, Los Altos and Mountain View.</p>
            <p class="small">We're currently building our team and partnering with businesses to bring you the best deals in the area. Whether you're looking for cheap haircuts or discounts on sushi restaurants, you'll soon get it. Sign-up below so you don't miss out. </p>
          </div>

          <!-- Signup Form  -->
          <%= form_for @new_consumer, url: consumers_path, method: "post", html: {class: "newsletter", id: "subscribe"} do |f| %>
              <input type="email" id="email" name="email" class="email" placeholder="Enter your email..." /> <button>Sign Me Up!</button> 
            <p class="note">We won't spam you. Pinky swear.</p>
            <div id="container_flash">
              <% flash.each do |key, value| %>
                <div class='flash' id='<%= key %>'>
                  <%= value %>
                </div>
              <% end %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</header>